name: Bun TypeScript Check

on:
  pull_request:
    branches:
      - master

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Set up .env file
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" > .env

      - name: Bun install
        run: bun install

      - name: Run bun tsc
        run: bun run tsc
